### ISSUE TITLE
Tech Talks #4

### ISSUE THREAD

**Issue by lack3r** [cyprus-developer-community/events#103]
### Featured Image

![Tech Talks #4 (1)](https://github.com/user-attachments/assets/3582d7c7-e4e5-4cc6-9458-e9cdd745bbd1)

### Event Description

RSVP [here](https://www.meetup.com/gdg-cyprus/events/303132587/)

Pale Blue, QBeat Technologies, and Deloitte Cyprus are thrilled to announce the fourth installment of the GDG Cyprus Tech Talks event series. Inspired by Google's renowned Tech Talks initiative, Tech Talks #4 promises an evening filled with insightful presentations, creative discussions, and meaningful networking for professionals and enthusiasts from the technical community.
This event series provides a platform for individuals and organizations to share technical knowledge across a wide array of topics - from foundational principles to cutting-edge innovations in technology. Tech Talks #4 will dive into both familiar and novel areas, appealing to participants of all levels of technical expertise.
Event Agenda
19:00 - 19:30: Gathering and registration
19:30 - 20:30: Technical presentations
20:30 - 21:30: Mingling & networking
Featured Talks
Navigating the Wireless Threat Landscape: Myths and Realities (30’)
Presented by Michalis Kyriacou, Co-founder and CEO of Intellectra Technologies, this talk will dissect the complexities of wireless security in today's interconnected world. The session will address common misconceptions surrounding cellular IoT networks and 5G, and explore the latest trends in cyber threats.
Asynchronous Programming in Python (30’)
Georgios Frangoulis, Software Developer Team Leader, will take attendees on an in-depth journey into asynchronous programming in Python. The session will explore essential concepts such as async and await, coroutines, and the IOLoop. It will also draw distinctions between concurrency and parallelism, providing real-life examples and an introduction to FastAPI and Tornado paradigms.
About the Organizers & Hosts
[Pale Blue](http://www.paleblueapps.com/) is a software engineering firm that excels in crafting custom software solutions for a global clientele, including partners in Canada, the UK, USA, Austria, and Cyprus. We pride ourselves on developing personalized software to meet unique client needs and operate as a startup studio, bringing our own innovative ideas to fruition.

[QBeat Technologies](https://www.qbeat.io/) is a reliable software partner, dedicated to delivering exceptional software solutions for a diverse range of multinational and national organizations. Specializing in the fintech, financial, and governmental sectors, QBeat crafts tailored solutions that help clients achieve excellence. With a global reach, the company has successfully served clients in Gibraltar, Luxembourg, Spain, Cyprus, and the UAE, showcasing its commitment to innovation and quality.

[Deloitte Cyprus](https://www.deloitte.com/cy/en.html) is a leading provider of professional services, offering audit, tax, consulting, and financial advisory services to a wide range of industries. With a strong presence in both the local and international markets, Deloitte Cyprus delivers innovative solutions that help businesses thrive in an ever-changing environment. Backed by a global network, the firm leverages its deep expertise to serve clients across sectors, consistently driving value and ensuring success in today’s competitive landscape.

[Google Developer Group Cyprus](https://gdg.community.dev/gdg-cyprus/) is an independent group of developers across Cyprus. We aim to run tech talks, workshops, study groups, networking events, and hackathons as well as partner with major initiatives in Cyprus to promote and support the technical community of Cyprus.

[More information and RSVP!](https://www.meetup.com/gdg-cyprus/events/303132587/)

### Location

Deloitte Cyprus

### Date

07.10.2024

### Time

19:00

### Duration

2h30m

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

**Comment by MYerouPaleBlue** [comment]
@saitonakamura Can you please approve this event? :)
