### ISSUE TITLE
CDCx Paphos

### ISSUE THREAD

**Issue by PatrickHeneise** [cyprus-developer-community/events#29]
### Event Description

![Ancient-Odeon-amphitheatre-in-Paphos-Archaeological-Park,-Cyprus](https://user-images.githubusercontent.com/74390/210996690-976dd4b6-3476-4e75-bace-5b5cfdf148a0.png)

The Cyprus Developer Community presents: **CDCx** Paphos with talks from [CyprusJS](https://github.com/cyprusjs) and [CyprusRust](https://github.com/cyprusrust)

- 17.30h Welcome
- 18.00h https://github.com/cyprusjs/CyprusJS/issues/40
- 18.30h Networking & Discussion
- 19.30h https://github.com/cyprusrust/CyprusRust/issues/1
- 20.00h Networking & Discussion

### Location

pallikarides-paphos

### Date

20.01.2023

### Time

17.30

### Duration

2h30m

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

### Broadcast by GitEvents

[![Eventbrite](https://img.shields.io/static/v1?label=eventbrite&logo=eventbrite&message=494881282237&color=F05537)](https://cdcx-paphos.eventbrite.ca)

**Comment by PatrickHeneise** [comment]
Eventbrite: https://www.eventbrite.ca/e/cdcx-paphos-tickets-494881282237

**Comment by PatrickHeneise** [comment]
@cyprus-developer-community/members just a few more days. Looking forward to see you all soon!

**Comment by terehov** [comment]
https://www.facebook.com/events/3474243976144530

**Comment by alexandr-bbm** [comment]
Hey folks, I am coming from Limassol by car - let me know if you need a ride

see you all 🙌

**Comment by PatrickHeneise** [comment]
@saitonakamura ^
