### ISSUE TITLE
Wrike Product Management Meetup 

### ISSUE THREAD

**Issue by WrikeTechClub** [cyprus-developer-community/events#32]
### Event Description

We continue growing [Wrike TechClub](https://www.wrike.com/techclub/) CY  community and happy to announce the event on Product Development challenges! Happy to see you there.

**Venue:** Wrike Office in Nicosia
**Entrance:** Free
**Drinks and Food:** Free
**Language:** English (at least for the talks)
**Registration:** https://pmcy-1.eventbrite.com/

Speakers and Talks:

[Anastasia Shevchenko](https://www.linkedin.com/in/anastasia--shevchenko/), Wrike –  Product research mistake cases
As a PM I do a lot of different researches. As an ever-learning PM, I’ve done a lot of mistakes in such researches.
Let me share 3 cases from my personal experience of things to avoid when doing research, and tips on how I keep myself from repeating them. They are universal, so even though I’ll be using my own examples, I hope you can apply them to your ongoing research as soon as you get home.
[Artyom Sarkisov](https://www.linkedin.com/in/artemsarkisov/), JetBrains – Topic to be announced

Follow us: www.wrike.com/techclub

### Location

wrike-hq-nicosia

### Date

15.12.2022

### Time

18.30

### Duration

2h

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

**Comment by PatrickHeneise** [comment]
@WrikeTechClub thanks! Could you please add and reference the location to the [locations file](https://github.com/cyprus-developer-community/events/blob/main/locations.json), the google link isn't usable on the website/other places.

**Comment by fogrew** [comment]
@PatrickHeneise Hi, Patrick! I added Wrike to locations.json. Could you please review PR #34 ? Let me know if I need to change something 🙏
