### ISSUE TITLE
Cyprus Kotlin User Group meetup

### ISSUE THREAD

**Issue by oldtuna** [cyprus-developer-community/events#33]
### Event Description

KUG Cyprus is for everyone who is interested in Kotlin. Doesn't matter whether you're a beginner or an expert, more into Android or Backend - we all want to learn more about Kotlin and have some fun together!

[Registration form](https://www.eventbrite.com/e/cyprus-kotlin-user-group-meetup-2012-tickets-478030140017?)

Agenda
18:00 - 18:30 - Gathering & Intro
18:30 - 19:15 - "Functional programming in Kotlin with Arrow"
Artemiy Mikhaylov (Android developer, inDrive)
In this talk, I will show some popular functional programming usage examples in Java and Kotlin and how the Arrow library can help you to use functional programming more efficiently.
19:15 - 21:00 - Networking
Special Guest - [Katerina Petrova](https://github.com/KaterinaPetrova) (Product Marketing Manager, ex-Developer Advocate for Kotlin Multiplatform Mobile, JetBrains). If you have questions about Kotlin Multiplatform or Kotlin in general, you will have the opportunity to discuss them with Katerina in an informal way.

### Location

Crowne Plaza, Limassol

### Date

20.12.2022

### Time

18.00

### Duration

3h

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

**Comment by PatrickHeneise** [comment]
Will the talks be in English?
