### ISSUE TITLE
Engineering leadership meetup #2: Case Study

### ISSUE THREAD

**Issue by WrikeTechClub** [cyprus-developer-community/events#54]
### Event Description

Venue: Wrike Office in Nicosia

Entrance: Free

Drinks and Food: Free

Language: English

Registration: https://www.eventbrite.com/e/engineering-leadership-meetup-2-case-study-tickets-624309746257

Welcome to the Wrike Engineering Leadership Meetup in Cyprus! This event is designed for professionals who lead a team or manage an engineering department. Our goal is to provide a space where you can network and share your experiences with fellow leaders.

During our meetup, we will cover a range of topics that are relevant to your daily challenges. We will explore techniques for motivating and developing your team members, planning and executing projects effectively, working with junior specialists, communicating with stakeholders, and implementing tactical approaches.

Unlike traditional conferences, we will not have any "talking head" presentations. Instead, we will use conversational formats such as case studies and live discussions to help you engage with the content on a deeper level. We believe that everyone has something valuable to contribute, which is why we will not be recording any videos. This will enable you to share your failures, mistakes, and lessons learned without fear of judgment. Our goal is to create a safe space where you can learn from each other, develop your leadership skills, network, and have fun.

O﻿ur Experts:
–﻿ [Vasily Sozykin](https://www.linkedin.com/in/sozykin-vasily-b2b723104/) – Technical Engineering, Wrike

–﻿ [Askhat Urazbaev](https://www.linkedin.com/in/urazbaev/) – Agile Transformation Lead, Exness

–﻿ [Kirill Peskov](https://www.linkedin.com/in/kirillpeskov/) – Head of Development @ World of Tanks, Wargaming

–﻿ Viktoria Dubrovskaja - Engineering manager @ UI platform team, inDrive

H﻿osts: [Ekaterina Rumiantseva](https://www.linkedin.com/in/ekaterina-rumiantceva/), Scrum master, Wrike, [Anton Anokhin](https://www.linkedin.com/in/antonanokhin/), Head of Employer branding, Wrike.

Topics to discuss:
–﻿ To be announced shortly

Follow us: [www.wrike.com/techclub](https://www.wrike.com/techclub/)
W﻿rike TechClub newsletter: [www.wrike.com/subscription-techclub/](https://www.wrike.com/subscription-techclub/)
Upcoming events: [www.eventbrite.com/o/wrike-techclub-27552199725](https://www.eventbrite.com/o/wrike-techclub-27552199725)

### Location

Wrike Office

### Date

18.05.2023

### Time

18.30

### Duration

3 hours

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

**Comment by jessgusclark** [comment]
I think the date on this is incorrect, it says '18.04.2023' when I think it should be '18.05.2023'.
