### ISSUE TITLE
CDC Meet & Greet Paphos April 2024 BBQ

### ISSUE THREAD

**Issue by framp** [cyprus-developer-community/events#95]
### Featured Image

![incredibly good looking developers networking](https://github.com/cyprus-developer-community/events/assets/611109/fc84074e-3243-4067-9d41-c3398781c04c)

![incredibly good looking developers stupidly trying to start a fire](https://github.com/cyprus-developer-community/events/assets/611109/a51c5496-a23c-4e8b-8923-e3d4aab16a92)

### Event Description

Meet and greet is an informal get together to discuss the latest in technology and science, and just have a pleasant BBQ

The event is completely free and you should bring whatever food and drinks you wish to consume. 
Partners and children are welcome!

Please sign up [on Eventbrite](https://www.eventbrite.com/e/cdc-meet-greet-paphos-bbq-tickets-872845844417) :)

### Location

picnic-site-peyia

### Date

13.04.2024

### Time

12.30

### Duration

4h00m

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct.org)

**Comment by stepanselyuk** [comment]
Date 13.03 misleading there if count presented photos :-) like the event already happened

**Comment by framp** [comment]
Thank you 🙌
